# GNU Make solution makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  euchre_config = debug
endif
ifeq ($(config),release)
  euchre_config = release
endif

PROJECTS := euchre

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

euchre:
ifneq (,$(euchre_config))
	@echo "==== Building euchre ($(euchre_config)) ===="
	@${MAKE} --no-print-directory -C . -f euchre.make config=$(euchre_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f euchre.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   euchre"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
